---

- name: Stop ldap
  service: name=slapd state=stopped
  when: 'ansible_hostname == server_ldap'

- name: Edit /etc/ldap/ldap.conf line by line.
  lineinfile:
    path: /etc/ldap/ldap.conf
    backup: yes
    regexp: '#URI	ldap://ldap.example.com ldap://ldap-master.example.com:666'
    line: "{{ item }}"
  loop:
    - 'uri ldap://{{ ldap_server_ip }}'
    - 'BINDDN {{ ldap_binddn }}'
    - 'BINDPW {{ vault_ldap_pass }}'
  
- name: Edit /etc/ldap/ldap.conf line by line.
  lineinfile:
    path: /etc/ldap/ldap.conf
    regexp: 'TLS_CACERT	/etc/ssl/certs/ca-certificates.crt'
    line: "{{ item }}"
  loop:
    - 'bind_timelimit 30'
    - 'timelimit 30'
    - 'sudoers_debug 0'
    - 'sudoers_timed yes'
    - 'TLS_CACERT      /etc/ssl/certs/ldapcacert.crt'
    
# What to do with the Cert??

- name: Install cert.crt to /etc/ssl/certs/ldapcacert.crt
  copy:
    src:  cert.crt
    dest: /etc/ssl/certs/ldapcacert.crt
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Edit /etc/nslcd.conf line by line.
  lineinfile:
    path: /etc/nslcd.conf
    backup: yes
    regexp: 'uri ldapi:///'
    line: 'uri ldap://{{ ldap_server_ip }}'

- name: Edit /etc/nslcd.conf line by line.
  lineinfile:
    path: /etc/nslcd.conf
    regexp: 'base dc=example,dc=net'
    line: 'base {{ ldap_base }}'

- name: Edit /etc/nslcd.conf line by line.
  lineinfile:
    path: /etc/nslcd.conf
    regexp: '#binddn cn=annonymous,dc=example,dc=net'
    line: 'binddn {{ ldap_binddn }}'

- name: Edit /etc/nslcd.conf line by line.
  lineinfile:
    path: /etc/nslcd.conf
    regexp: '#bindpw secret'
    line: 'bindpw {{ vault_ldap_pass }}'

- name: Edit /etc/nsswitch.conf line by line.
  lineinfile:
    path: /etc/nsswitch.conf
    backup: yes
    regexp: 'passwd:         files systemd'
    line: 'passwd:         files systemd ldap sss'

- name: Edit /etc/nsswitch.conf line by line.
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: 'group:          files systemd'
    line: 'group:          files systemd ldap sss'

- name: Edit /etc/nsswitch.conf line by line.
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: 'shadow:         files'
    line: 'shadow:         files ldap sss'

- name: Remove existing sudoers line in /etc/nsswitch.conf.
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: 'sudoers:        files sss'
    line: '# sudoers:        files sss'

- name: Edit /etc/nsswitch.conf line by line.
  lineinfile:
    path: /etc/nsswitch.conf
    line: 'sudoers:        files ldap'
    create: yes

- name: Restart ldap
  service: name=slapd state=restarted
  when: 'ansible_hostname == server_ldap'
