---

- name: Redistribute slurm.conf
  template:
    src: "slurm.conf.j2"
    dest: "{{ slurm_config_dir }}/slurm.conf"
    owner: "{{ __slurm_user_name }}"
    group: "{{ __slurm_group_name }}"
    mode: 0444
    backup: true

- name: Reconfigure via scontrol reconfigure
  shell: scontrol reconfigure