---

- name: Installation tasks
  tags: install
  block:
    - name: Include user creation tasks
      include_tasks: user.yml
      when: slurm_create_user

    - name: Include MariaDB installation tasks
      include_tasks: mariadb.yml
      when: install_mariadb

    - name: Check if Slurm is already installed in the correct version
      shell: "srun --version | rev | cut -d ' ' -f1 | rev"
      register: found_version
      when: slurm_from_source 

    - name: Include Munge configuration task
      include_tasks: munge.yml
      when: slurm_configure_munge

    - name: Include PMIx build task
      include_tasks: pmix.yml

    # - name: Print Slurm version
    #   debug:
    #     msg: "Slurm Version: {{ found_version }}"

    - name: Include controller installation tasks
      include_tasks: slurmctld.yml
      when: "'slurmservers' in group_names or 'controller' in slurm_roles"

    - name: Include execution host installation tasks
      include_tasks: slurmd.yml
      when: "'slurmexechosts' in group_names or 'exec' in slurm_roles"

    - name: Include slurmdbd installation tasks
      include_tasks: slurmdbd.yml
      when: "'slurmdbdservers' in group_names or 'dbd' in slurm_roles"

    - name: Include enroot installation tasks
      include_tasks: enroot.yml
      when: "'containerhosts' in group_names or 'container' in slurm_roles"

    - name: Include pyxis installation tasks
      include_tasks: pyxis.yml
      when: "'containerhosts' in group_names or 'container' in slurm_roles"

    - name: Import common tasks
      import_tasks: common.yml

    - name: Force systemd to reread configs
      systemd:
        daemon_reload: yes

    - name: Ensure slurmdbd is enabled and running
      service:
        name: "{{ slurmdbd_service_name }}"
        enabled: yes
        state: started
      when: "'slurmdbdservers' in group_names or 'dbd' in slurm_roles"

    - name: Ensure slurmctld is enabled and running
      service:
        name: "{{ slurmctld_service_name }}"
        enabled: yes
        state: started
      when: "'slurmservers' in group_names or 'controller' in slurm_roles"

    - name: Ensure slurmd is enabled and running
      service:
        name: "{{ slurmd_service_name }}"
        enabled: yes
        state: started
      when: "'slurmexechosts' in group_names or 'exec' in slurm_roles"


- name: Reconfiguration task
  tags: reconfigure
  block:
    - name: Import reconfiguration task
      import_tasks: config_redistribute.yml