---

- name: Create slurm group
  group:
    name: "{{ (slurm_user | default({})).group }}"
    gid: '64030'
    system: "{{ (slurm_user | default({})).system | default('yes') }}"
  when: (slurm_user | default({})).group is defined

- name: Create slurm user
  user:
    name: "{{ (slurm_user | default({})).name | default('slurm') }}"
    comment: "{{ (slurm_user | default({})).comment | default(omit) }}"
    uid: '64030'
    group: "{{ (slurm_user | default({})).group | default(omit) }}"
    groups: "{{ (slurm_user | default({})).groups | default(omit) }}"
    home: /nonexistent
    shell: /sbin/nologin
    system: "{{ (slurm_user | default({})).system | default('yes') }}"
